Models/ErrorViewModel.cs
using System;

namespace TestWebsite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Quote/Quote.cs
using System.ComponentModel.DataAnnotations;

namespace TestWebsite.Models.Quote
{
    public class Quote
    {
        [Display(Name = "Contact Name")]
        public string ContactName { get; set; }

        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

        [Display(Name = "Total Size (m2)")]
        public double TotalSize { get; set; }

        [Display(Name = "Total Rebuild Cost (£)")]
        public decimal TotalRebuildCost { get; set; }
        [Display(Name = "Flat Roof Cover")]
        public bool FlatRoofCover { get; set; } = false;
        [Display(Name = "Roof Size (m2)")]
        public double ?FlatRoofCoverBody { get; set; }
    }
}

Models/Quote/QuoteViewModel.cs
using System.Collections;
using System.Reflection;
using TestWebsite.Enums;

namespace TestWebsite.Models.Quote
{
    public class QuoteViewModel
    {
        public Quote Quote { get; set; }
        public GeneralEnum.Title Title { get; set; } = new GeneralEnum.Title();
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TestWebsite.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Controllers/QuoteFormController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using TestWebsite.Models.Quote;

namespace TestWebsite.Controllers
{
    public class QuoteFormController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Title = "Quote Form";

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateQuote(QuoteViewModel model)
        {
            if (model.Quote.TotalSize < 50)
            {
                return Json(new { successful = false, error = "The total size is too small for a quote." });
            }

            if (model.Quote.TotalRebuildCost < 100)
            {
                return Json(new { successful = false, error = "Total rebuild cost is too low." });
            }

            return Json(new { successful = true, reference = Guid.NewGuid() });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/QuoteForm/Index.cshtml
@using TestWebsite.Enums;
@using TestWebsite.Models.Quote;
@using static TestWebsite.Enums.GeneralEnum;
@model TestWebsite.Models.Quote.QuoteViewModel;
<form 
      method="post"
      asp-action="CreateQuote"
      asp-controller="QuoteForm"
      data-ajax="true" data-ajax-method="post"
      data-ajax-success="createQuoteSuccess"
      data-ajax-begin="createQuoteBegin"
      id="createQuoteForm">

    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col form-group">
            @Html.LabelFor(x => x.Quote.ContactName)
            @Html.TextBoxFor(x => x.Quote.ContactName, new { @class = "form-control" })
        </div>
        <div class="col form-group">
            @Html.LabelFor(x => x.Title)
            @Html.DropDownListFor(x => x.Title, new SelectList(Enum.GetValues(typeof(Title))),new { @class="form-control"})
        </div>
        <div class="col form-group">
            @Html.LabelFor(x => x.Quote.EmailAddress)
            @Html.TextBoxFor(x => x.Quote.EmailAddress, new { @class = "form-control", @type = "email" })
        </div>
    </div>
    <div class="row">
        <div class="col form-group">
            @Html.LabelFor(x => x.Quote.TotalSize)
            @Html.TextBoxFor(x => x.Quote.TotalSize, new { @class = "form-control", @type = "number", @step = "any" })
        </div>
        <div class="col form-group">
            @Html.LabelFor(x => x.Quote.TotalRebuildCost)
            @Html.TextBoxFor(x => x.Quote.TotalRebuildCost, new { @class = "form-control", @type = "number", @step = "0.10" })
        </div>
        <div class="col form-group">
            @Html.LabelFor(x => x.Quote.FlatRoofCover)
            @Html.CheckBox("FlatRoofCover", false)
            <br />
            @Html.LabelFor(x => x.Quote.FlatRoofCoverBody, new { @class = "pe-none", @id="FlatRoofCoverBodyLabel"})
            @Html.TextBoxFor(x => x.Quote.FlatRoofCoverBody, new { @class = "form-control pe-none",@id = "FlatRoofCoverBody", @type = "number",  @step = "any" })
        </div>
    </div>

    <button id="submitQuoteFormBtn" type="submit" class="btn btn-primary">Submit</button>
</form>

<script>
    createQuoteSuccess = function (result) {
        if (!result.successful) {
            addPeNone("FlatRoofCoverBody");
            addPeNone("FlatRoofCoverBodyLabel");
            removePeNone("submitQuoteFormBtn");
            $("#createQuoteForm").trigger("reset");
            alert(result.error);
            return;
        }
        alert("We have recieved your form, your reference is: " + result.reference + ".");
        addPeNone("FlatRoofCoverBody");
        addPeNone("FlatRoofCoverBodyLabel");
        removePeNone("submitQuoteFormBtn");
        $("#createQuoteForm").trigger("reset");
    }
    createQuoteBegin = function()
    {
        addPeNone("submitQuoteFormBtn");
    }

    $('#FlatRoofCover').click(function() {
        if(this.checked){
            removePeNone("FlatRoofCoverBody");
            removePeNone("FlatRoofCoverBodyLabel");
        }else{
            addPeNone("FlatRoofCoverBody");
            addPeNone("FlatRoofCoverBodyLabel");
        }
    });

    function addPeNone(id){
        $('#'+id).addClass("pe-none");
    }
    function removePeNone(id) {
        $('#'+id).removeClass("pe-none")
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestWebsite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QuoteForm" asp-action="Index">New Quote</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>